#!/bin/bash

API_URL=$(cat ${HOME}/.gsu_config|awk '{print $2}')

if [ "$1" = "attach" ]; then
    curl -d {} -H "Content-Type: application/json" -X POST ${API_URL}/attach/$2/$3
elif [ "$1" = "dettach" ]; then
    curl -d {} -H "Content-Type: application/json" -X POST ${API_URL}/detach/$2/$3
elif [ "$1" = "-la" ]; then
    curl -H "Content-Type: application/json" -X GET ${API_URL}/groups
elif [ "$1" = "-l" ]; then
    curl -H "Content-Type: application/json" -X GET ${API_URL}/groups/$2
else
    echo "gsu: switch GCP admin user roles."
    echo "usage:"
    echo "    gsu attach {user_name} {group_name}"
    echo "    gsu detach {user_name} {group_name}"
    echo "    gsu -la"
    echo "    gsu -l {user_name}"
fi